name: Image Optimization and Conversion

# Author: Ritaban Ghosh
# GitHub Profile: https://github.com/ritaban06

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  optimize-and-convert:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache apt packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('**/image-optimization.yml') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Install WebP Tools
        run: sudo apt-get update && sudo apt-get install webp -y
        
      - name: Convert Images to WebP and Remove Originals
        run: |
          find . -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.tiff" -o -iname "*.bmp" \) \
          -not -path "*/node_modules/*" \
          -not -path "*/.github/*" \
          -not -path "*/dist/*" \
          -not -path "*/build/*" \
          -not -path "*/public/images2/new/guest*" \
          -exec sh -c '
            for file do
              webp_path="${file%.*}.webp"
              if [ ! -f "$webp_path" ]; then
                if cwebp -q 60 "$file" -o "$webp_path"; then
                  echo "Converted $file to $webp_path"
                  rm "$file"
                  echo "Removed original file: $file"
                else
                  echo "Failed to convert $file"
                fi
              fi
            done
          ' sh {} +

      - name: Optimize WebP Images
        uses: ludeeus/action-image-optimizer@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          webp_quality: "80-90"
          compress_only: true

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add -A
          
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            exit 0
          fi
          
          git commit -m "Optimize and convert images to WebP"
          git pull --rebase origin ${{ github.head_ref || 'main' }}
          git push origin HEAD:${{ github.head_ref || 'main' }}
